### ISSUE TITLE
Make package PSR4 compliant, and publish on composer?

### ISSUE THREAD

**Issue by afk11** [lastguest/murmurhash-php#2]
I am interested in using this in a project, would you be interested in a small rewrite to make it compatible for PSR4? I'd then like to put it onto packagist for composer to be able to load it. 

I can submit a small PR refactoring things to set it up if you like?

**Comment by lastguest** [comment]
Sure! I'll update it as soon as I can :)

**Comment by lastguest** [comment]
Done in 57c5b213844c481f5874281443e78210109e2dba
