### ISSUE TITLE
Broken with PHP > 5 ?

### ISSUE THREAD

**Issue by DontShootMe** [lastguest/murmurhash-php#3]
It seem to be broken with PHP > 5
Test case : 
[ideone => PHP 5.6](https://ideone.com/hKx0HD)
[codepad => PHP 5.2](http://codepad.org/ii09wKua)

**Comment by DontShootMe** [comment]
Finally not broken, but maybe a configuration where the result seem to be different !
I don't know why, where and how to look for this difference ! ! !
[this is ok](http://codepad.viper-7.com/mfv1Vw)

**Comment by lastguest** [comment]
Seems like a problem with PHP on some 32bit systems.
If integer operations overflow the PHP_INT_MAX value it will be converted to float ( http://php.net/manual/en/language.types.integer.php ) incurring on precision error.

I will look on a solution based on an arbitrary precision extension.

**Comment by DontShootMe** [comment]
yes it is !
I have found it !
but, too late . . . :-( this doesn’t help you .
Many thanks.
